// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/server/server.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyRpc_SayHello_FullMethodName = "/rpc_demo.MyRpc/SayHello"
)

// MyRpcClient is the client API for MyRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyRpcClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type myRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMyRpcClient(cc grpc.ClientConnInterface) MyRpcClient {
	return &myRpcClient{cc}
}

func (c *myRpcClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MyRpc_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyRpcServer is the server API for MyRpc service.
// All implementations must embed UnimplementedMyRpcServer
// for forward compatibility.
type MyRpcServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMyRpcServer()
}

// UnimplementedMyRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyRpcServer struct{}

func (UnimplementedMyRpcServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMyRpcServer) mustEmbedUnimplementedMyRpcServer() {}
func (UnimplementedMyRpcServer) testEmbeddedByValue()               {}

// UnsafeMyRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyRpcServer will
// result in compilation errors.
type UnsafeMyRpcServer interface {
	mustEmbedUnimplementedMyRpcServer()
}

func RegisterMyRpcServer(s grpc.ServiceRegistrar, srv MyRpcServer) {
	// If the following call pancis, it indicates UnimplementedMyRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyRpc_ServiceDesc, srv)
}

func _MyRpc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyRpcServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyRpc_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyRpcServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MyRpc_ServiceDesc is the grpc.ServiceDesc for MyRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_demo.MyRpc",
	HandlerType: (*MyRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MyRpc_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/server/server.proto",
}
